### ISSUE TITLE
Korekcije

### ISSUE THREAD

**Issue by mi14008mosic** [MATF-RG17/RG075-super-dario#5]
Da li projekat zadovoljava prag i mogu li bez predlozenih korekcija da izadjem na ispit? Zaista imam malo vremena.

**Comment by mi14008mosic** [comment]
Izvinite zbog ovakvih pitanja. Ako postoji opcija da se oduzme predvidjeni broj bodova zbog takvog koda, ja je prihvatam  (pod uslovom da projekat u ovom obliku zadovoljava prag).

**Comment by ivan-cukic-matf** [comment]
Možete da izadjete na ispit.
